---
languageCode:           "en-us"
title:                  "NNPN"
disableLiveReload:      true
watch:                  true
preservetaxonomynames:  true

params:
  description:   "National New Play Network"
  author:        "Jordana"
  title:         "National New Play Network"

taxonomies:
  related: related

blackfriday:
  fractions: false

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: related
    weight: 100
...
