---
baseURL:                "http://localhost:1313"
languageCode:           "en-us"
title:                  "NNPN"
disableLiveReload:      true
watch:                  true
preservetaxonomynames:  true

params:
  description:   "National New Play Network"
  author:        "Jordana"
  title:    "National New Play Network"
  no_index:      true
...
