version: 2
jobs:
  hugo:
    docker:
      - image: cibuilds/hugo:0.55
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project/site -d ~/project/public
      - run:
          name: "Debugging build"
          command: pwd && ls -al ~/project && ls -al ~/project/public
      - persist_to_workspace:
          root: /root/project
          paths:
            - ~
  webpack:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: "Debugging attach"
          command: pwd && ls -al ~/project && ls -al ~/project/public
      - run: |
          npm install
          npm run build
      - run:
          name: "Debugging webpack"
          command: pwd && ls -al ~/project && ls -al ~/project/public
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - public
  verify:
    docker:
      - image: cibuilds/hugo:0.55
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: "Debugging attach"
          command: pwd && ls -al ~/project && ls -al ~/project/public
      - run:
          name: "Test site"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
  deploy:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - "31:d0:dd:9d:39:e6:7f:ac:3a:0b:bc:6a:09:68:0b:15"
      - run:
          name: "Copy files"
          command: yes | scp -o StrictHostKeyChecking=no -r ~/project/public/* $SSH_USER@$SSH_HOST:/var/www/html
workflows:
  version: 2
  workflow:
    jobs:
      - hugo
      - webpack:
          requires:
            - hugo
      - verify:
          requires:
            - webpack
      - deploy:
          requires:
            - verify
